#!/usr/bin/env bash
set -euo pipefail

if ! dpkg-query -W -f='${Status}' openjdk-17-jdk-headless 2>/dev/null | grep -q 'install ok installed'; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq openjdk-17-jdk-headless
fi
java -version
